# Generated by Django 2.2.3 on 2019-07-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_app_label', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(default='time', max_length=20),
        ),
    ]
