# Generated by Django 2.2.4 on 2019-10-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_app_label', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='use_google_calendar',
            field=models.BooleanField(default=False),
        ),
    ]
