# Generated by Django 2.2.4 on 2019-09-25 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meeting_app_label', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='images/profile_image.png', upload_to='profile_users')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userProfileInfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
